### PR TITLE
fix: fix sign command options & show global options in subcommand help

### PR DESCRIPTION
**Pull request by WhistlingZephyr**
Hello! It's me again. I was using this repo's CLI again and noticed that in v0.6.0's `sign` command was giving me this error:
image
And after realizing from the check of https://github.com/violentmonkey/amo-upload/blob/959bc26a2fdc2c471465e6e4e5631f75d5e4da45/src/bin.ts#L64 my error only complained about every required option other than `addonVersion` which was explicitly defined inside the subcommand in https://github.com/violentmonkey/amo-upload/blob/959bc26a2fdc2c471465e6e4e5631f75d5e4da45/src/bin.ts#L29-L35 I found that for the `sign` command any of the global options weren't being passed at all. I noticed the `list` subcommand already has a solution for that in https://github.com/violentmonkey/amo-upload/blob/959bc26a2fdc2c471465e6e4e5631f75d5e4da45/src/bin.ts#L96-L102 so I copied it over to the `sign` command as well.

I also added the `showGlobalOptions` flag for commander.js mentioned in their [readme](https://github.com/tj/commander.js/tree/970ecae402b253de691e6a9066fea22f38fe7431?tab=readme-ov-file#more-configuration-2) and [example](https://github.com/tj/commander.js/blob/970ecae402b253de691e6a9066fea22f38fe7431/examples/global-options-nested.js#L1-L28) that I found while looking up info on the initial error.

> `showGlobalOptions`: show a section with the global options from the parent command(s)

I know v0.6.0 was pushed 10 months ago so I'm a bit late to the party, but would still appreciate having this CLI fix merged. Thanks!

### CODE REVIEW

**Comment by WhistlingZephyr** [comment]
Uhh, the CI is failing with
```
UsageError: This project is configured to use yarn because /home/runner/work/amo-upload/amo-upload/package.json has a "packageManager" field
``` 
I did notice the repo was mistakenly using `yarn` in `.husky/pre-push`: https://github.com/violentmonkey/amo-upload/blob/959bc26a2fdc2c471465e6e4e5631f75d5e4da45/.husky/pre-push#L4

Not sure where else it's using that though (couldn't find a `packageManager` field in the `package.json` file), let me update that part and see if it fixes.

**Comment by WhistlingZephyr** [comment]
No luck, CI is still failing...

**Comment by WhistlingZephyr** [comment]
Could you try clearing caches from <https://github.com/violentmonkey/amo-upload/actions/caches> maybe? I think it could be pulling old cache where `node_modules` still used `yarn`. I can't find any more traces of `yarn` in the code.

**Comment by gera2ld** [comment]
Could you rebase to the lastest `main` branch? I've updated the github actions.

**Comment by WhistlingZephyr** [comment]
Done, CI works now.

**Pull request merged**
